(function(){
  'use strict';
  const cfg=window.BubbaHubDirectoryConfig||{};
  const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
  let items=[], filtered=[], page=1, perPage=12, cols=3, view='grid', map=null, markers=[];
  function root(){return document.getElementById('dirGrid')||document.querySelector('#bubbahub-app #dirGrid')}
  function setup(){const grid=root();if(!grid||grid.dataset.bhViews==='1')return;grid.dataset.bhViews='1';
    const layout=document.createElement('div');layout.className='bh-directory-layout';grid.parentNode.insertBefore(layout,grid);layout.appendChild(grid);grid.classList.add('bh-directory-results');
    const toolbar=document.createElement('div');toolbar.className='bh-directory-toolbar';toolbar.innerHTML='<button type="button" data-bh-view="grid" class="is-active">Grid</button><button type="button" data-bh-view="list">List</button><button type="button" data-bh-view="map">Map</button><label>Columns <select data-bh-cols><option>2</option><option>3</option><option>4</option><option>5</option><option>6</option></select></label><label>Per page <select data-bh-page><option value="12">12</option><option value="24">24</option><option value="48">48</option></select></label><button type="button" data-bh-advanced>Advanced filters</button><div class="bh-directory-advanced" data-bh-advanced-panel><label>Age range<input data-f-age placeholder="e.g. 0-3"></label><label>Town / city<input data-f-city placeholder="e.g. Paignton"></label><label>Day<input data-f-day placeholder="e.g. Monday"></label><label>Price<input data-f-price placeholder="e.g. free"></label><label>Term time<select data-f-term><option value="">Any</option><option value="yes">Term time</option><option value="no">All year</option></select></label></div>';
    grid.parentNode.insertBefore(toolbar,grid);
    const pager=document.createElement('div');pager.className='bh-directory-pagination';layout.appendChild(pager);
    const mapEl=document.createElement('div');mapEl.className='bh-directory-map';layout.appendChild(mapEl);
    toolbar.addEventListener('click',e=>{const b=e.target.closest('[data-bh-view]');if(b){view=b.dataset.bhView;toolbar.querySelectorAll('[data-bh-view]').forEach(x=>x.classList.toggle('is-active',x===b));layout.classList.toggle('is-map',view==='map');grid.classList.toggle('is-list',view==='list');render();}if(e.target.closest('[data-bh-advanced]'))toolbar.querySelector('[data-bh-advanced-panel]').classList.toggle('is-open')});
    toolbar.addEventListener('change',e=>{if(e.target.matches('[data-bh-cols]')){cols=Math.max(2,Math.min(6,+e.target.value||3));grid.style.setProperty('--bh-cols',cols);render();}if(e.target.matches('[data-bh-page]')){perPage=+e.target.value||12;page=1;render();}if(e.target.matches('[data-f-term]')){page=1;render()}});
    toolbar.addEventListener('input',()=>{page=1;render()});
    grid.style.setProperty('--bh-cols',cols);
    fetchData();
  }
  async function fetchData(){if(!cfg.api)return;try{const r=await fetch(cfg.api,{headers:{'X-WP-Nonce':cfg.nonce||''}});const d=await r.json();items=Array.isArray(d.items)?d.items:[];filtered=items.slice();render();}catch(e){renderMessage('Unable to load directory listings.');}}
  function val(f,k){return String((f||{})[k]??'').toLowerCase()}
  function apply(){const a=document.querySelector('[data-f-age]')?.value.toLowerCase().trim()||'',c=document.querySelector('[data-f-city]')?.value.toLowerCase().trim()||'',d=document.querySelector('[data-f-day]')?.value.toLowerCase().trim()||'',p=document.querySelector('[data-f-price]')?.value.toLowerCase().trim()||'',t=document.querySelector('[data-f-term]')?.value||'';filtered=items.filter(x=>{const f=x.fields||{};return (!a||val(f,'age_range').includes(a))&&(!c||val(f,'city').includes(c)||String(x.title).toLowerCase().includes(c))&&(!d||val(f,'day').includes(d)||val(f,'timetable').includes(d))&&(!p||val(f,'price').includes(p)||(+p===0&&val(f,'is_free')==='1'))&&(!t||(t==='yes'&&['yes','term time','term-time'].some(z=>val(f,'term_time').includes(z)))||(t==='no'&&!val(f,'term_time').includes('term')));});}
  function image(x){const f=x.fields||{},v=f.images||f.image||'';if(/^https?:\/\//i.test(v))return v;return ''}
  function card(x){const f=x.fields||{},loc=[f.city,f.region].filter(Boolean).join(', '),age=f.age_range||'',price=f.price||'',im=image(x);return '<article class="bh-card bh-directory-card" data-id="'+esc(x.id)+'">'+(im?'<img class="bh-card-image" src="'+esc(im)+'" alt="">':'')+'<span class="bh-tag">Group</span><h3>'+esc(x.title)+'</h3>'+(loc?'<p><strong>Location:</strong> '+esc(loc)+'</p>':'')+(age?'<p><strong>Age range:</strong> '+esc(age)+'</p>':'')+(price?'<p><strong>Price:</strong> '+esc(price)+'</p>':'')+'<div class="bh-card-actions"><button class="bh-btn secondary" data-group-modal="'+esc(x.id)+'">View details</button></div></article>'}
  function render(){apply();const grid=root(),pager=document.querySelector('.bh-directory-pagination');if(!grid)return;const total=filtered.length,pages=Math.max(1,Math.ceil(total/perPage));if(page>pages)page=pages;const start=(page-1)*perPage,shown=view==='map'?filtered:filtered.slice(start,start+perPage);grid.innerHTML=shown.length?shown.map(card).join(''):'<div class="bh-empty"><h3>No matching groups</h3><p>Try changing the filters.</p></div>';if(pager){pager.innerHTML='';if(view!=='map'&&pages>1){for(let i=1;i<=pages;i++){const b=document.createElement('button');b.textContent=i;b.className=i===page?'is-active':'';b.onclick=()=>{page=i;render();};pager.appendChild(b);}}}if(view==='map')renderMap(filtered);else if(map){map.remove();map=null;document.querySelector('.bh-directory-map').innerHTML='';}}
  function renderMessage(m){const g=root();if(g)g.innerHTML='<div class="bh-empty">'+esc(m)+'</div>'}
  function renderMap(data){const el=document.querySelector('.bh-directory-map');if(!el)return;function init(){if(!window.L)return;if(map)map.remove();el.innerHTML='';map=L.map(el,{scrollWheelZoom:false}).setView([50.4,-3.6],10);L.tileLayer(cfg.mapTiles,{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(map);markers=[];const valid=data.filter(x=>isFinite(+x.latitude)&&isFinite(+x.longitude));valid.forEach(x=>{const m=L.marker([+x.latitude,+x.longitude]).addTo(map).bindPopup('<strong>'+esc(x.title)+'</strong><br><button type="button" data-group-modal="'+esc(x.id)+'">View details</button>');markers.push(m);});if(valid.length){const b=L.latLngBounds(valid.map(x=>[+x.latitude,+x.longitude]));map.fitBounds(b.pad(.15));}}if(window.L)init();else{const css=document.createElement('link');css.rel='stylesheet';css.href='https://unpkg.com/leaflet@1.9.4/dist/leaflet.css';document.head.appendChild(css);const js=document.createElement('script');js.src='https://unpkg.com/leaflet@1.9.4/dist/leaflet.js';js.onload=init;document.head.appendChild(js);}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',setup);else setup();
})();
