(function(){'use strict';
const C=window.BubbaHubConfig||{},root=document.getElementById('bubbahub-app');if(!root)return;
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
async function api(path,opt={}){opt.headers=Object.assign({'Content-Type':'application/json'},opt.headers||{});if(C.nonce)opt.headers['X-WP-Nonce']=C.nonce;opt.credentials='same-origin';const r=await fetch(C.api+path,opt);let j={};try{j=await r.json()}catch(e){}if(!r.ok)throw new Error(j.message||'Request failed');return j}
const field=(g,...keys)=>{for(const k of keys){const v=g?.custom_fields?.[k]?.value??g?.[k];if(v!==undefined&&v!==null&&String(v)!=='')return v}return ''};
const text=v=>String(v??'').replace(/<[^>]+>/g,'').replace(/&nbsp;/gi,' ').trim();
function tags(g){let t=Array.isArray(g.terms)?g.terms.slice():[];const raw=field(g,'post_tags','tags');if(raw)t=t.concat(String(raw).split(/[,\n#]+/).map(x=>x.trim()).filter(Boolean));return [...new Set(t)].slice(0,18)}
function days(g){const raw=field(g,'business_hours','openinghours','opening_hours');if(!raw)return [];const names=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];if(typeof raw==='object')return names.filter(d=>raw[d]||raw[d.toLowerCase()]);const s=String(raw);return names.filter(d=>new RegExp('(?:^|[\\n;,|])\\s*'+d+'\\s*(?::|-|–|—|\\s)\\s*(?!closed|closed\\b|no sessions)','i').test(s)||new RegExp('(?:^|[\\n;,|])\\s*'+d+'\\s*$','im').test(s));}
function hours(g){const raw=field(g,'business_hours','openinghours','opening_hours');if(!raw)return [];if(typeof raw==='object')return Object.entries(raw).map(([d,v])=>[d,v]).filter(([,v])=>String(v??'').trim());return String(raw).split(/\n|;|\|/).map(x=>x.trim()).filter(Boolean).map(x=>{const m=x.match(/^([A-Za-z]+(?:day)?)\s*[:\-–—]\s*(.*)$/);return m?[m[1],m[2]]:[x,''];}).filter(x=>x[0]);}
function location(g){return [field(g,'street','address'),field(g,'city','town'),field(g,'region'),field(g,'zip','postcode')].filter(Boolean).join(', ')}
function price(g){const p=field(g,'price');if(!p)return 'Free';return /^£/.test(String(p).trim())?String(p):'£'+String(p)}
function map(g){const lat=parseFloat(field(g,'latitude','manual_lat','lat')),lng=parseFloat(field(g,'longitude','manual_lng','lng'));const addr=location(g);if(Number.isFinite(lat)&&Number.isFinite(lng)){const z=15;const bbox=[lng-0.012,lng+0.012,lat-0.008,lat+0.008].join(',');const src='https://www.openstreetmap.org/export/embed.html?bbox='+encodeURIComponent(bbox)+'&layer=mapnik&marker='+encodeURIComponent(lat+','+lng);return `<div class="bh-listing-map-wrap"><iframe title="Map location" loading="lazy" src="${esc(src)}"></iframe><a class="bh-map-link" target="_blank" rel="noopener" href="https://www.openstreetmap.org/?mlat=${encodeURIComponent(lat)}&mlon=${encodeURIComponent(lng)}#map=16/${encodeURIComponent(lat)}/${encodeURIComponent(lng)}">Open larger map ↗</a><div class="bh-map-label"><strong>${esc(g.title)}</strong><span>${esc(addr||'Location')}</span></div></div>`}return `<div class="bh-listing-map-empty"><strong>Location</strong><span>${esc(addr||'Location details not provided')}</span></div>`}
function editUrl(){return C.pageUrls?.leader||C.directoryUrl||'#'}
function render(g){const tagsList=tags(g),hs=hours(g),active=days(g),age=field(g,'age_range','ages'),session=field(g,'session_length'),term=field(g,'term_time','term-time'),address=location(g),website=field(g,'website'),email=field(g,'email'),desc=g.content||g.raw_content||g.excerpt||'';const category=tagsList[0]||'LOCAL FAMILY GROUP';const id=g.id||field(g,'id');const featured=field(g,'featured','is_featured');const other=field(g,'other_locations','other_locations_list','locations');const logged=!!C.loggedIn;const canEdit=logged&&((C.user?.roles||[]).some(r=>['administrator','bubbahub_leader','leader','leaderpro'].includes(r)));
root.innerHTML=`<div class="bh-listing-page"><section class="bh-listing-hero"><div class="bh-listing-hero-main"><div class="bh-listing-chips"><span>${esc(String(category).toUpperCase())}</span><span>ID: ${esc(id)}</span><button data-action="fav">♡ Favourite</button><button data-action="visited">✓ Mark visited</button></div><h1>${esc(g.title)}</h1>${address?`<p class="bh-listing-address">📍 ${esc(address)}</p>`:''}</div><div class="bh-listing-management"><span>Listing Management<small>Manage venue details & status</small></span>${canEdit?`<a class="bh-listing-edit" href="${esc(editUrl())}">✎ Edit this Listing</a>`:''}<a class="bh-listing-back" href="${esc(C.directoryUrl||'#')}">← Back</a></div></section><section class="bh-listing-quick"><div><small>AGE RANGE</small><strong>${esc(age||'Not specified')}</strong></div><div><small>SESSION LENGTH</small><strong>${esc(session||'Not specified')}</strong></div><div><small>TERM TIME</small><strong>${esc(term||'All year')}</strong></div><div><small>PRICE</small><strong>${esc(price(g))}</strong></div></section><div class="bh-listing-columns"><main><section class="bh-listing-panel bh-listing-about"><div class="bh-panel-heading"><h2>About the Experience</h2>${canEdit?`<a href="${esc(editUrl())}">✎ Edit Description</a>`:''}</div><div class="bh-listing-content">${desc||'<p>More information about this local group or service will be added soon.</p>'}</div></section><section class="bh-listing-panel bh-listing-map-panel"><h2>Venue &amp; Map Location</h2>${map(g)}</section></main><aside><section class="bh-listing-panel"><h2>Keywords &amp; Tags</h2><div class="bh-listing-tags">${tagsList.length?tagsList.map(t=>`<span>#${esc(t.replace(/^#/,'').trim())}</span>`).join(''):'<span>No tags added</span>'}</div></section><section class="bh-listing-panel"><h2>Opening Hours &amp; Schedule</h2><p class="bh-panel-sub">Weekly schedule, session times, and class details.</p><div class="bh-hours">${hs.length?hs.map(([d,v])=>`<div><strong>${esc(d)}</strong><span>${esc(text(v)||'Closed / No sessions')}</span></div>`).join(''):active.length?active.map(d=>`<div><strong>${esc(d)}</strong><span>Active</span></div>`).join(''):'<div><strong>Schedule</strong><span>Not provided</span></div>'}</div></section><section class="bh-listing-panel bh-other"><div class="bh-other-head"><div><h2>Other Locations</h2><p>More from this organiser</p></div><b>0</b></div><div class="bh-other-empty">${other?esc(text(other)):'No other locations listed under this organizer.'}</div></section><section class="bh-listing-book"><h2>Ready to Join?</h2><p>Secure your spot for this activity right away.</p><button data-book>Book My Space Now →</button></section></aside></div></div>`;
const fav=root.querySelector('[data-action="fav"]'),visited=root.querySelector('[data-action="visited"]');fav?.addEventListener('click',async()=>{if(!logged){alert('Please sign in to save listings.');return}try{await api('saved',{method:'POST',body:JSON.stringify({object_type:'group_favorite',object_id:+id})});fav.textContent='♥ Favourited'}catch(e){alert(e.message)}});visited?.addEventListener('click',async()=>{if(!logged){alert('Please sign in to mark this listing as visited.');return}try{await api('saved',{method:'POST',body:JSON.stringify({object_type:'group_visited',object_id:+id})});visited.textContent='✓ Visited'}catch(e){alert(e.message)}});root.querySelector('[data-book]')?.addEventListener('click',()=>{if(website)window.open(String(website),'_blank','noopener');else if(email)window.location.href='mailto:'+email;else alert('Booking information is not available for this listing yet. Please contact the organiser.');});}
(async()=>{const slug=(C.initialGroup||location.pathname.match(/\/directory\/group\/([^/]+)/)?.[1]||'').replace(/\/$/,'');if(!slug){root.innerHTML='<div class="bh-main"><div class="bh-empty"><h2>Listing not found</h2><a class="bh-btn" href="'+esc(C.directoryUrl||'#')+'">Back to directory</a></div></div>';return}try{const g=await api('group/'+encodeURIComponent(slug));render(g)}catch(e){root.innerHTML='<div class="bh-main"><div class="bh-empty"><h2>We could not load this listing</h2><p>'+esc(e.message)+'</p><a class="bh-btn" href="'+esc(C.directoryUrl||'#')+'">Back to directory</a></div></div>'}})();
})();