(function(){
const C=window.BubbaHubConfig||{},root=document.getElementById('bubbahub-app');if(!root)return;
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
const val=(g,k)=>g.custom_fields?.[k]?.value||'';const clean=s=>String(s??'').replace(/<[^>]+>/g,'').trim();
const field=(g,...ks)=>{for(const k of ks){const v=val(g,k);if(v)return v}return''};
const location=(g)=>[field(g,'city','town'),field(g,'region','county')].filter(Boolean).join(', ')||field(g,'location','venue');
const age=g=>field(g,'age_range','ages','age');const price=g=>field(g,'price','cost','session_price');
const hours=g=>field(g,'business_hours','opening_hours','hours','timetable','schedule');
const days=g=>{const h=hours(g);return ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'].filter(d=>new RegExp('\\b'+d.slice(0,3)+'(?:day)?\\b','i').test(h))};
const flag=(g,...ks)=>ks.some(k=>['1','yes','true','on','featured','popular'].includes(String(val(g,k)).toLowerCase()));
const badges=g=>{let b=[];const dt=Date.parse(g.date||g.post_date||g.modified||'');if(dt&&!isNaN(dt)&&(Date.now()-dt)<30*86400000)b.push('<span class="bh-badge bh-badge-new">New</span>');if(flag(g,'popular','is_popular'))b.push('<span class="bh-badge bh-badge-popular">Popular</span>');if(flag(g,'featured','is_featured'))b.push('<span class="bh-badge bh-badge-featured">Featured</span>');if(val(g,'term_time')||flag(g,'term_time_only'))b.push('<span class="bh-badge bh-badge-term">Term Time</span>');return b.join('')};
function card(g){const a=age(g),p=price(g),loc=location(g),ds=days(g),desc=clean(g.excerpt||g.content).slice(0,155);return `<article class="bh-listing-card bh-listing-card-v2"><div class="bh-listing-media">${g.image?`<img src="${esc(g.image)}" alt="${esc(g.title)}" loading="lazy">`:'<div class="bh-listing-placeholder">BubbaHub</div>'}<div class="bh-card-badges">${badges(g)}</div><button class="bh-listing-save" data-upgrade-save="${g.id}" aria-label="Save group">♡</button></div><div class="bh-listing-body"><h3 class="bh-listing-title"><button class="bh-title-link" data-upgrade-detail="${g.id}">${esc(g.title)}</button></h3>${loc?`<p class="bh-listing-location">📍 ${esc(loc)}</p>`:''}<div class="bh-listing-key-meta">${a?`<span><strong>Age range</strong>${esc(a)}</span>`:''}${p?`<span><strong>Price</strong>${esc(p)}</span>`:''}</div>${ds.length?`<div class="bh-listing-days"><strong>Days active</strong>${ds.map(d=>`<span>${esc(d.slice(0,3))}</span>`).join('')}</div>`:''}${desc?`<p class="bh-listing-description">${esc(desc)}</p>`:''}<div class="bh-listing-card-actions"><button type="button" class="bh-checkin-btn" data-upgrade-save="${g.id}">♡ Fav Group</button><button type="button" class="bh-checkin-btn" data-upgrade-compare="${g.id}">＋ Compare Group</button><button type="button" class="bh-listing-view" data-upgrade-detail="${g.id}">View details</button></div></div></article>`}
function detail(g){const loc=location(g),a=age(g),p=price(g),h=hours(g),ds=days(g),terms=(g.terms||[]).map(x=>`<span class="bh-detail-tag">${esc(x)}</span>`).join(''),website=field(g,'website','url'),email=field(g,'email'),phone=field(g,'phone','telephone');root.insertAdjacentHTML('beforeend',`<div class="bh-modal open bh-upgrade-detail" id="bhUpgradeDetail"><div class="bh-modalbox bh-group-modal bh-detail-modal"><button class="bh-detail-close" data-upgrade-close aria-label="Close">×</button><div class="bh-detail-hero"><div class="bh-detail-image">${g.image?`<img src="${esc(g.image)}" alt="${esc(g.title)}">`:'<div class="bh-listing-placeholder">BubbaHub</div>'}<div class="bh-detail-badges">${badges(g)}</div></div><div class="bh-detail-summary"><div class="bh-listing-category">${esc((g.terms||[])[0]||'BubbaHub listing')}</div><h1>${esc(g.title)}</h1><div class="bh-detail-tags">${terms}</div>${loc?`<div class="bh-detail-location">📍 ${esc(loc)}</div>`:''}<div class="bh-detail-key-grid">${a?`<div><strong>Age range</strong><span>${esc(a)}</span></div>`:''}${p?`<div><strong>Price</strong><span>${esc(p)}</span></div>`:''}</div><div class="bh-detail-actions">${website?`<a class="bh-btn" href="${esc(website)}" target="_blank" rel="noopener">Visit website</a>`:''}${email?`<a class="bh-btn secondary" href="mailto:${esc(email)}">Email</a>`:''}${phone?`<a class="bh-btn secondary" href="tel:${esc(phone)}">Call</a>`:''}</div></div></div><div class="bh-detail-sections"><section class="bh-detail-panel"><h2>About this listing</h2><div class="bh-group-content">${g.content||esc(g.excerpt||'')}</div></section><aside class="bh-detail-panel"><h2>Listing information</h2><div class="bh-detail-info">${loc?`<div><strong>Location</strong><span>${esc(loc)}</span></div>`:''}${a?`<div><strong>Age range</strong><span>${esc(a)}</span></div>`:''}${p?`<div><strong>Price</strong><span>${esc(p)}</span></div>`:''}<div><strong>Days active</strong><div class="bh-detail-days">${ds.length?ds.map(d=>`<span class="bh-day-pill">${esc(d)}</span>`).join(''):'<span class="bh-muted">See timetable</span>'}</div></div>${h?`<div><strong>Opening / session times</strong><span>${esc(clean(h))}</span></div>`:''}</div></aside></div><div class="bh-detail-contact-row">${email?`<a href="mailto:${esc(email)}">${esc(email)}</a>`:''}${phone?`<a href="tel:${esc(phone)}">${esc(phone)}</a>`:''}${website?`<a href="${esc(website)}" target="_blank" rel="noopener">Website</a>`:''}</div></div></div>`);const m=root.querySelector('#bhUpgradeDetail');m.querySelectorAll('[data-upgrade-close]').forEach(b=>b.onclick=()=>m.remove());m.onclick=e=>{if(e.target===m)m.remove()}}
async function init(){if(C.initialPage&&C.initialPage!=='directory')return;try{const r=await fetch(C.api+'bootstrap',{headers:C.nonce?{'X-WP-Nonce':C.nonce}:{}}),d=await r.json(),groups=d.groups||[],grid=root.querySelector('#bhListingGrid');if(!grid||!groups.length)return;grid.innerHTML=groups.map(card).join('');grid.querySelectorAll('[data-upgrade-detail]').forEach(b=>b.onclick=()=>{const g=groups.find(x=>+x.id===+b.dataset.upgradeDetail);if(g)detail(g)});grid.querySelectorAll('[data-upgrade-save]').forEach(b=>b.onclick=async()=>{if(!C.loggedIn){alert('Please sign in to save listings.');return}try{const h=C.nonce?{'Content-Type':'application/json','X-WP-Nonce':C.nonce}:{'Content-Type':'application/json'};await fetch(C.api+'saved',{method:'POST',headers:h,body:JSON.stringify({object_type:'group_favorite',object_id:+b.dataset.upgradeSave})});grid.querySelectorAll(`[data-upgrade-save="${b.dataset.upgradeSave}"]`).forEach(x=>{x.textContent=x.tagName==='BUTTON'&&x.classList.contains('bh-listing-save')?'♥':'♥ Fav Group';x.classList.add('is-checked')})}catch(e){alert('Could not save this listing.')}})}catch(e){}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,50));else setTimeout(init,50);
})();