<?php
if(!defined('ABSPATH'))exit;

/**
 * BubbaHub Google Sheets import manager.
 * Uses the existing Google Apps Script JSON endpoint and writes real rows into bh_group.
 * No demo data is generated. Existing records are matched by Google id first, then username.
 */
class BubbaHubGoogleImport{
 const ACTION='bubbahub_google_import';
 public static function boot(){add_action('admin_menu',[__CLASS__,'menu'],31);add_action('admin_post_'.self::ACTION,[__CLASS__,'run']);}
 public static function menu(){add_submenu_page('bubbahub','Import Google Sheets','Import Google Sheets','manage_bubbahub','bubbahub-google-import',[__CLASS__,'page']);}
 private static function settings(){return class_exists('BubbaHubGoogleSync')?BubbaHubGoogleSync::settings():[];}
 public static function page(){if(!current_user_can('manage_bubbahub'))return;$last=get_option('bubbahub_google_import_last',[]);echo '<div class="wrap"><h1>Import Google Sheets</h1><p>Import real listing rows from the configured Google Sheets API into the BubbaHub directory.</p><p><strong>No demo data is created.</strong> Existing listings are updated when their Google ID or organiser username matches.</p>';if(isset($_GET['bh_import'])){$ok=sanitize_key($_GET['bh_import'])==='success';echo '<div class="notice notice-'.($ok?'success':'error').'"><p>'.esc_html($ok?'Google Sheets import completed. Check the import summary below.':'Google Sheets import could not retrieve any usable rows. Check the Google Sync settings and endpoint.').'</p></div>';}echo '<form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="'.esc_attr(self::ACTION).'">';wp_nonce_field(self::ACTION,'bubbahub_google_import_nonce');submit_button('Import / update listings now');echo '</form>';if($last)echo '<h2>Last import</h2><p>'.esc_html($last['time']??'').' — '.absint($last['count']??0).' listing(s) processed.</p></div>';else echo '</div>';}
 public static function run(){if(!current_user_can('manage_bubbahub')||!check_admin_referer(self::ACTION,'bubbahub_google_import_nonce'))wp_die('Permission denied.');$s=self::settings();$rows=[];foreach(['main_url','term_url'] as $key){$url=esc_url_raw($s[$key]??'');if(!$url)continue;$r=wp_remote_get($url,['timeout'=>30,'redirection'=>5,'headers'=>['Accept'=>'application/json'],'user-agent'=>'BubbaHub/'.BUBBAHUB_VERSION]);if(is_wp_error($r))continue;$code=wp_remote_retrieve_response_code($r);$d=json_decode(wp_remote_retrieve_body($r),true);if($code>=200&&$code<300&&is_array($d))$rows=array_merge($rows,self::rows($d));}if(!$rows){wp_safe_redirect(add_query_arg(['page'=>'bubbahub-google-import','bh_import'=>'error'],admin_url('admin.php')));exit;}$rows=self::dedupe($rows);$count=0;$created=0;$updated=0;foreach($rows as $r){$title=self::val($r,['title','name','group_name','listing_name']);if($title==='')continue;$gid=self::val($r,['id','listing_id','group_id']);$user=self::val($r,['wp_username','organizer_username','organiser_username','organizer','organiser']);$id=$gid?self::find('_bubbahub_google_id',$gid):0;if(!$id&&$user)$id=self::find('_bubbahub_google_wp_username',$user);$args=['post_type'=>'bh_group','post_status'=>'publish','post_title'=>sanitize_text_field($title)];$description=self::val($r,['description','content','post_content','about']);if($description!=='')$args['post_content']=wp_kses_post($description);if($id){$args['ID']=$id;$result=wp_update_post($args,true);$updated++;}else{$result=wp_insert_post($args,true);$created++;}$id=is_wp_error($result)?0:absint($result);if(!$id)continue;if($gid)update_post_meta($id,'_bubbahub_google_id',sanitize_text_field($gid));if($user)update_post_meta($id,'_bubbahub_google_wp_username',sanitize_user($user));foreach(self::fields() as $field=>$aliases){$v=self::val($r,$aliases);if($v==='')continue;if(in_array($field,['featured','is_free','term_time'],true))$v=self::yes($v)?'1':'0';update_post_meta($id,'_bubbahub_'.$field,sanitize_text_field($v));}update_post_meta($id,'_bubbahub_google_last_import',current_time('mysql'));$count++;}update_option('bubbahub_google_import_last',['time'=>current_time('mysql'),'count'=>$count,'created'=>$created,'updated'=>$updated]);wp_safe_redirect(add_query_arg(['page'=>'bubbahub-google-import','bh_import'=>$count?'success':'error'],admin_url('admin.php')));exit;}
 private static function rows($d){foreach(['data','rows','groups','listings'] as $k)if(isset($d[$k])&&is_array($d[$k])){$d=$d[$k];break;}if(!is_array($d))return[];$out=[];foreach($d as $row){if(!is_array($row))continue;$x=[];foreach($row as $k=>$v)$x[sanitize_title_with_dashes(strtolower(trim((string)$k)))]=is_scalar($v)?trim((string)$v):'';if($x)$out[]=$x;}return$out;}
 private static function dedupe($rows){$out=[];$seen=[];foreach($rows as $r){$id=self::val($r,['id','listing_id','group_id']);$user=self::val($r,['wp_username','organizer_username','organiser_username']);$key=$id!==''?'i:'.strtolower($id):($user!==''?'u:'.strtolower($user):'t:'.sanitize_title(self::val($r,['title','name','group_name'])));if(isset($seen[$key]))$out[$seen[$key]]=array_merge($out[$seen[$key]],$r);else{$seen[$key]=count($out);$out[]=$r;}}return$out;}
 private static function find($key,$value){$ids=get_posts(['post_type'=>'bh_group','post_status'=>'any','posts_per_page'=>1,'fields'=>'ids','meta_key'=>$key,'meta_value'=>$value]);return absint($ids[0]??0);}
 private static function val($r,$aliases){foreach($aliases as $a){$k=sanitize_title_with_dashes(strtolower(trim($a)));if(isset($r[$k])&&$r[$k]!=='')return$r[$k];}return'';}
 private static function yes($v){return in_array(strtolower(trim((string)$v)),['1','true','yes','y','on','free'],true);}
 private static function fields(){return['images'=>['images','image','gallery','gallery_images'],'tags'=>['tags','tag'],'category'=>['category','categories'],'featured'=>['is_featured','featured','featured_listing'],'street'=>['address','street','address1'],'city'=>['city','town','postal_town'],'region'=>['region','county'],'zip'=>['zip','postcode','post_code','postal_code'],'latitude'=>['manual_lat','latitude','lat'],'longitude'=>['manual_lng','longitude','lng','lon'],'timetable'=>['timetable','schedule'],'business_hours'=>['openinghours','opening_hours','business_hours','opening hours'],'website'=>['website','url'],'email'=>['email'],'facebook'=>['facebook'],'instagram'=>['instagram'],'is_free'=>['is_free','free','free_session'],'price'=>['price','cost'],'term_time'=>['term_time','term-time','term time','termtime'],'age_range'=>['age_range','age range'],'session_length'=>['session_length','session length'],'day'=>['day','days'],'sen'=>['sen']];}
}
BubbaHubGoogleImport::boot();
