<?php
if (!defined('ABSPATH')) exit;
/**
 * BubbaHub 4.0 Booking, Payments & Leader Wallet engine.
 * Bank transfer is deliberately non-instant: customer pays BubbaHub, invoice is issued,
 * admin confirms receipt, then funds become available to the leader wallet.
 */
class BubbaHubFinance {
  const VERSION='4.0.0';
  public static function init(){
    add_action('init',[__CLASS__,'maybe_upgrade']);
    add_action('rest_api_init',[__CLASS__,'routes']);
    add_action('admin_menu',[__CLASS__,'admin_menu'],30);
    add_action('admin_post_bh_finance_save',[__CLASS__,'save_settings']);
    add_action('admin_post_bh_finance_booking',[__CLASS__,'booking_action']);
    add_action('bubbahub_daily_payouts',[__CLASS__,'process_automatic_payouts']);
    if(!wp_next_scheduled('bubbahub_daily_payouts')) wp_schedule_event(time()+300,'daily','bubbahub_daily_payouts');
  }
  private static function table($name){global $wpdb;return $wpdb->prefix.'bubbahub_'.$name;}
  public static function maybe_upgrade(){if(get_option('bubbahub_finance_db_version')===self::VERSION)return;global $wpdb;require_once ABSPATH.'wp-admin/includes/upgrade.php';$c=$wpdb->get_charset_collate();
    dbDelta("CREATE TABLE ".self::table('bookings')." (id bigint unsigned NOT NULL AUTO_INCREMENT,booking_ref varchar(40) NOT NULL,customer_id bigint unsigned NOT NULL,leader_id bigint unsigned NOT NULL,listing_id bigint unsigned NOT NULL,session_id bigint unsigned NULL,session_date date NULL,start_time time NULL,ticket_quantity int unsigned NOT NULL DEFAULT 1,gross_amount decimal(12,2) NOT NULL DEFAULT 0,platform_fee decimal(12,2) NOT NULL DEFAULT 0,provider_fee decimal(12,2) NOT NULL DEFAULT 0,net_amount decimal(12,2) NOT NULL DEFAULT 0,payment_method varchar(30) NOT NULL,status varchar(40) NOT NULL,invoice_id bigint unsigned NULL,provider_ref varchar(190) NULL,customer_note text NULL,created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,paid_at datetime NULL,PRIMARY KEY(id),UNIQUE KEY booking_ref(booking_ref),KEY customer_id(customer_id),KEY leader_id(leader_id),KEY listing_id(listing_id)) $c;");
    dbDelta("CREATE TABLE ".self::table('wallets')." (leader_id bigint unsigned NOT NULL,available decimal(12,2) NOT NULL DEFAULT 0,pending decimal(12,2) NOT NULL DEFAULT 0,lifetime_earnings decimal(12,2) NOT NULL DEFAULT 0,lifetime_payouts decimal(12,2) NOT NULL DEFAULT 0,updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(leader_id)) $c;");
    dbDelta("CREATE TABLE ".self::table('wallet_transactions')." (id bigint unsigned NOT NULL AUTO_INCREMENT,leader_id bigint unsigned NOT NULL,type varchar(30) NOT NULL,reference varchar(80) NULL,amount decimal(12,2) NOT NULL,description text NULL,balance_after decimal(12,2) NOT NULL DEFAULT 0,created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(id),KEY leader_id(leader_id)) $c;");
    dbDelta("CREATE TABLE ".self::table('payouts')." (id bigint unsigned NOT NULL AUTO_INCREMENT,payout_ref varchar(40) NOT NULL,leader_id bigint unsigned NOT NULL,amount decimal(12,2) NOT NULL,method varchar(30) NOT NULL,status varchar(30) NOT NULL,provider_ref varchar(190) NULL,reason text NULL,created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,processed_at datetime NULL,PRIMARY KEY(id),UNIQUE KEY payout_ref(payout_ref),KEY leader_id(leader_id)) $c;");
    dbDelta("CREATE TABLE ".self::table('invoices')." (id bigint unsigned NOT NULL AUTO_INCREMENT,invoice_number varchar(40) NOT NULL,booking_id bigint unsigned NOT NULL,customer_id bigint unsigned NOT NULL,amount decimal(12,2) NOT NULL,status varchar(30) NOT NULL DEFAULT 'unpaid',due_at datetime NULL,created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,paid_at datetime NULL,PRIMARY KEY(id),UNIQUE KEY invoice_number(invoice_number),KEY booking_id(booking_id)) $c;");
    $s=self::settings();$s['platform_fee_percent']=isset($s['platform_fee_percent'])?(float)$s['platform_fee_percent']:5;$s['payout_minimum']=isset($s['payout_minimum'])?(float)$s['payout_minimum']:10;$s['bank_enabled']=isset($s['bank_enabled'])?(int)$s['bank_enabled']:1;$s['stripe_enabled']=isset($s['stripe_enabled'])?(int)$s['stripe_enabled']:1;$s['paypal_enabled']=isset($s['paypal_enabled'])?(int)$s['paypal_enabled']:1;$s['payment_notice']=$s['payment_notice']??'Payments may include third-party payment processing charges where applicable.';$s['bank_notice']=$s['bank_notice']??'Bank transfer is not an instant payment. BubbaHub will issue an invoice, confirm receipt and then release eligible funds.';update_option('bubbahub_finance_settings',$s);update_option('bubbahub_finance_db_version',self::VERSION);
  }
  private static function settings(){return (array)get_option('bubbahub_finance_settings',[]);}
  private static function money($n){return number_format((float)$n,2,'.','');}
  private static function ref($prefix){return strtoupper($prefix).'-'.wp_generate_password(10,false,false);}
  private static function current_leader(){return current_user_can('manage_options')?0:(int)get_current_user_id();}
  private static function wallet($leader){global $wpdb;$t=self::table('wallets');$w=$wpdb->get_row($wpdb->prepare("SELECT * FROM $t WHERE leader_id=%d",$leader),ARRAY_A);if(!$w){$wpdb->insert($t,['leader_id'=>$leader]);$w=$wpdb->get_row($wpdb->prepare("SELECT * FROM $t WHERE leader_id=%d",$leader),ARRAY_A);}return $w;}
  private static function transaction($leader,$type,$ref,$amount,$description){global $wpdb;$w=self::wallet($leader);$new=round((float)$w['available']+(float)$amount,2);$wpdb->update(self::table('wallets'),['available'=>$new,'lifetime_earnings'=>(float)$w['lifetime_earnings']+($amount>0?$amount:0),'updated_at'=>current_time('mysql')],['leader_id'=>$leader]);$wpdb->insert(self::table('wallet_transactions'),['leader_id'=>$leader,'type'=>$type,'reference'=>$ref,'amount'=>$amount,'description'=>$description,'balance_after'=>$new]);return $new;}
  private static function booking_price($listing,$posted){$price=null;if($listing){$meta=get_post_meta($listing);foreach($meta as $k=>$v){if(preg_match('/price|cost|fee/i',$k)&&isset($v[0])&&is_numeric(preg_replace('/[^0-9.]/','',$v[0]))){$price=(float)preg_replace('/[^0-9.]/','',$v[0]);break;}}}return $price===null?(float)$posted:$price;}
  private static function invoice($booking,$customer,$amount){global $wpdb;$num='BH-INV-'.gmdate('Y').'-'.str_pad((string)wp_rand(1,999999),6,'0',STR_PAD_LEFT);$wpdb->insert(self::table('invoices'),['invoice_number'=>$num,'booking_id'=>$booking,'customer_id'=>$customer,'amount'=>$amount,'status'=>'unpaid','due_at'=>gmdate('Y-m-d H:i:s',time()+7*DAY_IN_SECONDS)]);return (int)$wpdb->insert_id;}
  public static function routes(){
    register_rest_route('bubbahub/v1','/bookings',['methods'=>'POST','callback'=>[__CLASS__,'create_booking'],'permission_callback'=>function(){return is_user_logged_in();}]);
    register_rest_route('bubbahub/v1','/bookings',['methods'=>'GET','callback'=>[__CLASS__,'my_bookings'],'permission_callback'=>function(){return is_user_logged_in();}]);
    register_rest_route('bubbahub/v1','/bookings/(?P<id>\d+)/pay',['methods'=>'POST','callback'=>[__CLASS__,'start_payment'],'permission_callback'=>function(){return is_user_logged_in();}]);
    register_rest_route('bubbahub/v1','/leader/bookings',['methods'=>'GET','callback'=>[__CLASS__,'leader_bookings'],'permission_callback'=>function(){return current_user_can('manage_options')||self::is_leader();}]);
    register_rest_route('bubbahub/v1','/leader/bookings/(?P<id>\d+)',['methods'=>'POST','callback'=>[__CLASS__,'update_booking'],'permission_callback'=>function(){return current_user_can('manage_options')||self::is_leader();}]);
    register_rest_route('bubbahub/v1','/leader/wallet',['methods'=>'GET','callback'=>[__CLASS__,'leader_wallet'],'permission_callback'=>function(){return current_user_can('manage_options')||self::is_leader();}]);
    register_rest_route('bubbahub/v1','/leader/wallet/settings',['methods'=>'POST','callback'=>[__CLASS__,'save_payout_settings_api'],'permission_callback'=>function(){return self::is_leader();}]);
    register_rest_route('bubbahub/v1','/leader/wallet/payout',['methods'=>'POST','callback'=>[__CLASS__,'request_payout'],'permission_callback'=>function(){return self::is_leader();}]);
    register_rest_route('bubbahub/v1','/finance/config',['methods'=>'GET','callback'=>function(){return ['stripe'=>!empty(self::settings()['stripe_enabled']),'paypal'=>!empty(self::settings()['paypal_enabled']),'bank'=>!empty(self::settings()['bank_enabled']),'notice'=>self::settings()['payment_notice']??''];},'permission_callback'=>'__return_true']);
  }
  private static function is_leader(){return in_array('bubbahub_leader',(array)(wp_get_current_user()->roles),true)||in_array('leader',(array)(wp_get_current_user()->roles),true)||in_array('leaderpro',(array)(wp_get_current_user()->roles),true);}
  public static function create_booking($r){global $wpdb;$p=$r->get_json_params();$listing=absint($p['listing_id']??0);$leader=absint($p['leader_id']??get_post_field('post_author',$listing));if(!$listing||!$leader)return new WP_Error('invalid_booking','A valid listing and leader are required',['status'=>400]);$method=sanitize_key($p['payment_method']??'stripe');$settings=self::settings();if($method==='bank_transfer'&&!empty($settings['bank_enabled'])===false)return new WP_Error('bank_disabled','Bank transfer is currently unavailable',['status'=>400]);if($method==='stripe'&&!empty($settings['stripe_enabled'])===false)return new WP_Error('stripe_disabled','Stripe is currently unavailable',['status'=>400]);if($method==='paypal'&&!empty($settings['paypal_enabled'])===false)return new WP_Error('paypal_disabled','PayPal is currently unavailable',['status'=>400]);$qty=max(1,absint($p['ticket_quantity']??1));$gross=round(self::booking_price($listing,$p['amount']??0)*$qty,2);$fee=round($gross*((float)($settings['platform_fee_percent']??5)/100),2);$provider=0;$net=round($gross-$fee-$provider,2);$status=$method==='bank_transfer'?'awaiting_bank_transfer':'pending_payment';$ref=self::ref('BH');$wpdb->insert(self::table('bookings'),['booking_ref'=>$ref,'customer_id'=>get_current_user_id(),'leader_id'=>$leader,'listing_id'=>$listing,'session_id'=>absint($p['session_id']??0)?:null,'session_date'=>sanitize_text_field($p['session_date']??'')?:null,'start_time'=>sanitize_text_field($p['start_time']??'')?:null,'ticket_quantity'=>$qty,'gross_amount'=>$gross,'platform_fee'=>$fee,'provider_fee'=>$provider,'net_amount'=>$net,'payment_method'=>$method,'status'=>$status,'customer_note'=>sanitize_textarea_field($p['customer_note']??'')]);$id=(int)$wpdb->insert_id;$invoice=0;if($method==='bank_transfer')$invoice=self::invoice($id,get_current_user_id(),$gross);$wpdb->update(self::table('bookings'),['invoice_id'=>$invoice?:null],['id'=>$id]);return ['id'=>$id,'booking_id'=>$id,'booking_ref'=>$ref,'status'=>$status,'amount'=>self::money($gross),'net_to_leader'=>self::money($net),'invoice_id'=>$invoice?:null,'notice'=>$method==='bank_transfer'?($settings['bank_notice']??''):($settings['payment_notice']??'')];}
  public static function my_bookings(){global $wpdb;$u=get_current_user_id();return $wpdb->get_results($wpdb->prepare("SELECT b.*,p.post_title, i.invoice_number FROM ".self::table('bookings')." b LEFT JOIN {$wpdb->posts} p ON p.ID=b.listing_id LEFT JOIN ".self::table('invoices')." i ON i.id=b.invoice_id WHERE b.customer_id=%d ORDER BY b.created_at DESC",$u),ARRAY_A);}
  public static function start_payment($r){global $wpdb;$id=absint($r['id']);$b=$wpdb->get_row($wpdb->prepare('SELECT * FROM '.self::table('bookings').' WHERE id=%d AND customer_id=%d',$id,get_current_user_id()),ARRAY_A);if(!$b)return new WP_Error('not_found','Booking not found',['status'=>404]);if($b['payment_method']==='bank_transfer')return ['status'=>'awaiting_bank_transfer','invoice_id'=>$b['invoice_id'],'message'=>'Bank transfer is invoiced and is not an instant payment.'];if($b['payment_method']==='stripe')return ['provider'=>'stripe','status'=>'checkout_required','message'=>'Connect Stripe Checkout/Payment Element using the booking id.','booking_id'=>$id];if($b['payment_method']==='paypal')return ['provider'=>'paypal','status'=>'order_required','message'=>'Create the PayPal order using the booking id.','booking_id'=>$id];return new WP_Error('payment_method','Unsupported payment method',['status'=>400]);}
  public static function leader_bookings(){global $wpdb;$u=self::current_leader();$where=$u?'WHERE b.leader_id='.(int)$u:'';return $wpdb->get_results("SELECT b.*,p.post_title,u.user_email FROM ".self::table('bookings')." b LEFT JOIN {$wpdb->posts} p ON p.ID=b.listing_id LEFT JOIN {$wpdb->users} u ON u.ID=b.customer_id $where ORDER BY b.created_at DESC",ARRAY_A);}
  public static function update_booking($r){global $wpdb;$id=absint($r['id']);$p=$r->get_json_params();$u=self::current_leader();$b=$wpdb->get_row($wpdb->prepare('SELECT * FROM '.self::table('bookings').' WHERE id=%d',$id),ARRAY_A);if(!$b||($u&&$b['leader_id']!=$u))return new WP_Error('not_found','Booking not found',['status'=>404]);$allowed=['confirmed','cancelled','attended','no_show','paid'];$status=sanitize_key($p['status']??'');if(!in_array($status,$allowed,true))return new WP_Error('status','Invalid booking status',['status'=>400]);if($status==='paid'&&$b['status']!=='paid'){ $wpdb->update(self::table('bookings'),['status'=>'paid','paid_at'=>current_time('mysql')],['id'=>$id]);self::transaction((int)$b['leader_id'],'booking',$b['booking_ref'],(float)$b['net_amount'],'Booking '.$b['booking_ref'].' earnings');}else{$wpdb->update(self::table('bookings'),['status'=>$status],['id'=>$id]);}return ['success'=>true,'status'=>$status];}
  public static function leader_wallet(){global $wpdb;$u=self::current_leader();if(!$u)return ['wallet'=>null,'transactions'=>[]];return ['wallet'=>self::wallet($u),'transactions'=>$wpdb->get_results($wpdb->prepare('SELECT * FROM '.self::table('wallet_transactions').' WHERE leader_id=%d ORDER BY id DESC LIMIT 100',$u),ARRAY_A),'payouts'=>$wpdb->get_results($wpdb->prepare('SELECT * FROM '.self::table('payouts').' WHERE leader_id=%d ORDER BY id DESC LIMIT 50',$u),ARRAY_A),'payout_settings'=>self::payout_settings($u)];}
  private static function payout_settings($u){$d=['mode'=>'manual','method'=>'stripe','threshold'=>10,'interval'=>'weekly','stripe_connect_account'=>'','paypal_payout_email'=>'','bank_account_name'=>'','bank_sort_code'=>'','bank_account_number'=>''];$x=(array)get_user_meta($u,'bubbahub_payout_settings',true);return array_merge($d,$x);}
  public static function save_payout_settings_api($r){$u=get_current_user_id();$p=$r->get_json_params();$mode=in_array(($p['mode']??''),['manual','automatic'],true)?$p['mode']:'manual';$method=in_array(($p['method']??''),['stripe','paypal','bank_transfer'],true)?$p['method']:'stripe';if($method==='bank_transfer')$mode='automatic';$x=['mode'=>$mode,'method'=>$method,'threshold'=>max(0,(float)($p['threshold']??10)),'interval'=>in_array(($p['interval']??''),['daily','weekly','fortnightly','monthly'],true)?$p['interval']:'weekly','stripe_connect_account'=>sanitize_text_field($p['stripe_connect_account']??''),'paypal_payout_email'=>sanitize_email($p['paypal_payout_email']??''),'bank_account_name'=>sanitize_text_field($p['bank_account_name']??''),'bank_sort_code'=>sanitize_text_field($p['bank_sort_code']??''),'bank_account_number'=>sanitize_text_field($p['bank_account_number']??'')];update_user_meta($u,'bubbahub_payout_settings',$x);return $x;}
  public static function request_payout($r){$u=get_current_user_id();$p=self::payout_settings($u);if($p['method']==='bank_transfer')return new WP_Error('bank_transfer_auto_only','Bank-transfer payouts are automatic only.',['status'=>400]);if($p['mode']!=='manual')return new WP_Error('automatic_mode','Your payout mode is automatic.',['status'=>400]);return self::create_payout($u);}
  private static function create_payout($u){global $wpdb;$w=self::wallet($u);$settings=self::settings();$min=max((float)$payoutMin=(float)($settings['payout_minimum']??10),(float)(self::payout_settings($u)['threshold']??0));if((float)$w['available']<$min)return new WP_Error('threshold','Wallet has not reached the payout threshold.',['status'=>400]);$p=self::payout_settings($u);$ref=self::ref('PAY');$wpdb->insert(self::table('payouts'),['payout_ref'=>$ref,'leader_id'=>$u,'amount'=>$w['available'],'method'=>$p['method'],'status'=>'queued','reason'=>'Leader payout request']);$id=(int)$wpdb->insert_id;return ['id'=>$id,'payout_ref'=>$ref,'amount'=>self::money($w['available']),'method'=>$p['method'],'status'=>'queued'];}
  public static function process_automatic_payouts(){global $wpdb;$leaders=$wpdb->get_col('SELECT leader_id FROM '.self::table('wallets'));foreach($leaders as $u){$p=self::payout_settings((int)$u);if($p['mode']!=='automatic')continue;$w=self::wallet((int)$u);$min=max((float)($p['threshold']??0),(float)(self::settings()['payout_minimum']??10));if((float)$w['available']>=$min)self::create_payout((int)$u);}}
  public static function admin_menu(){add_submenu_page('bubbahub','Bookings & Payments','Bookings & Payments','manage_options','bubbahub-finance',[__CLASS__,'admin_page']);}
  public static function admin_page(){if(!current_user_can('manage_options'))return;$s=self::settings();global $wpdb;$bookings=$wpdb->get_results('SELECT b.*,p.post_title FROM '.self::table('bookings').' b LEFT JOIN '.$wpdb->posts.' p ON p.ID=b.listing_id ORDER BY b.created_at DESC LIMIT 100',ARRAY_A);echo '<div class="wrap"><h1>BubbaHub 4.0 — Bookings, Payments & Wallets</h1><form method="post" action="'.esc_url(admin_url('admin-post.php')).'">'.wp_nonce_field('bh_finance_save','bh_finance_nonce',true,false).'<input type="hidden" name="action" value="bh_finance_save"><table class="form-table"><tr><th>Platform fee %</th><td><input name="platform_fee_percent" type="number" step="0.01" value="'.esc_attr($s['platform_fee_percent']??5).'"> <p class="description">Deducted from each booking before leader wallet credit.</p></td></tr><tr><th>Minimum payout</th><td><input name="payout_minimum" type="number" step="0.01" value="'.esc_attr($s['payout_minimum']??10).'"> </td></tr><tr><th>Payment methods</th><td><label><input type="checkbox" name="stripe_enabled" value="1" '.checked(!empty($s['stripe_enabled']),true,false).'> Stripe</label> <label><input type="checkbox" name="paypal_enabled" value="1" '.checked(!empty($s['paypal_enabled']),true,false).'> PayPal</label> <label><input type="checkbox" name="bank_enabled" value="1" '.checked(!empty($s['bank_enabled']),true,false).'> Bank transfer</label></td></tr><tr><th>Payment notice</th><td><textarea name="payment_notice" rows="2" cols="70">'.esc_textarea($s['payment_notice']??'Payments may include third-party payment processing charges where applicable.').'</textarea></td></tr><tr><th>Bank transfer notice</th><td><textarea name="bank_notice" rows="2" cols="70">'.esc_textarea($s['bank_notice']??'Bank transfer is not an instant payment. BubbaHub will issue an invoice, confirm receipt and then release eligible funds.').'</textarea></td></tr></table><p><button class="button button-primary">Save finance settings</button></p></form><hr><h2>Recent bookings</h2><table class="widefat striped"><thead><tr><th>Reference</th><th>Listing</th><th>Amount</th><th>Method</th><th>Status</th><th>Action</th></tr></thead><tbody>';foreach($bookings as $b){echo '<tr><td>'.esc_html($b['booking_ref']).'</td><td>'.esc_html($b['post_title']).'</td><td>£'.esc_html(self::money($b['gross_amount'])).'</td><td>'.esc_html($b['payment_method']).'</td><td>'.esc_html($b['status']).'</td><td>';if($b['payment_method']==='bank_transfer'&&$b['status']==='awaiting_bank_transfer')echo '<form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="bh_finance_booking"><input type="hidden" name="booking_id" value="'.(int)$b['id'].'">'.wp_nonce_field('bh_finance_booking','bh_booking_nonce',true,false).'<button class="button">Confirm bank payment</button></form>';echo '</td></tr>';}echo '</tbody></table></div>';}
  public static function save_settings(){if(!current_user_can('manage_options')||!check_admin_referer('bh_finance_save','bh_finance_nonce'))wp_die('Unauthorised');$s=self::settings();$s['platform_fee_percent']=max(0,(float)($_POST['platform_fee_percent']??5));$s['payout_minimum']=max(0,(float)($_POST['payout_minimum']??10));$s['stripe_enabled']=!empty($_POST['stripe_enabled'])?1:0;$s['paypal_enabled']=!empty($_POST['paypal_enabled'])?1:0;$s['bank_enabled']=!empty($_POST['bank_enabled'])?1:0;$s['payment_notice']=sanitize_textarea_field($_POST['payment_notice']??'');$s['bank_notice']=sanitize_textarea_field($_POST['bank_notice']??'');update_option('bubbahub_finance_settings',$s);wp_safe_redirect(admin_url('admin.php?page=bubbahub-finance&updated=1'));exit;}
  public static function booking_action(){if(!current_user_can('manage_options')||!check_admin_referer('bh_finance_booking','bh_booking_nonce'))wp_die('Unauthorised');global $wpdb;$id=absint($_POST['booking_id']);$b=$wpdb->get_row($wpdb->prepare('SELECT * FROM '.self::table('bookings').' WHERE id=%d',$id),ARRAY_A);if($b&&$b['status']==='awaiting_bank_transfer'){$wpdb->update(self::table('bookings'),['status'=>'paid','paid_at'=>current_time('mysql')],['id'=>$id]);$wpdb->update(self::table('invoices'),['status'=>'paid','paid_at'=>current_time('mysql')],['id'=>$b['invoice_id']]);self::transaction((int)$b['leader_id'],'booking',$b['booking_ref'],(float)$b['net_amount'],'Bank-transfer booking '.$b['booking_ref'].' confirmed by BubbaHub.');}wp_safe_redirect(admin_url('admin.php?page=bubbahub-finance'));exit;}
}
BubbaHubFinance::init();
