<?php
if (!defined('ABSPATH')) exit;
/**
 * BubbaHub 4.0 payment-provider layer.
 * Keeps provider credentials out of the front-end and turns the existing booking records
 * into real Stripe Checkout and PayPal Orders. Bank transfer remains invoice/manual-confirmation only.
 */
class BubbaHubFinanceProviders {
  public static function init(){
    add_action('rest_api_init',[__CLASS__,'routes'],20);
    add_action('rest_pre_dispatch',[__CLASS__,'intercept_payment'],5,3);
    add_action('bubbahub_daily_payouts',[__CLASS__,'process_queued_payouts'],20);
    add_action('admin_menu',[__CLASS__,'admin_menu'],35);
    add_action('admin_post_bh_provider_save',[__CLASS__,'save']);
  }
  private static function settings(){return (array)get_option('bubbahub_finance_settings',[]);}
  private static function table($n){global $wpdb;return $wpdb->prefix.'bubbahub_'.$n;}
  private static function booking($id,$uid=0){global $wpdb;$sql='SELECT * FROM '.self::table('bookings').' WHERE id=%d';$args=[$id];if($uid){$sql.=' AND customer_id=%d';$args[]=$uid;}return $wpdb->get_row($wpdb->prepare($sql,$args),ARRAY_A);}
  private static function mark_paid($b,$provider_ref){global $wpdb;if($b['status']==='paid')return;$wpdb->update(self::table('bookings'),['status'=>'paid','provider_ref'=>sanitize_text_field($provider_ref),'paid_at'=>current_time('mysql')],['id'=>$b['id']]);if(!empty($b['invoice_id']))$wpdb->update(self::table('invoices'),['status'=>'paid','paid_at'=>current_time('mysql')],['id'=>$b['invoice_id']]);$w=$wpdb->get_row($wpdb->prepare('SELECT * FROM '.self::table('wallets').' WHERE leader_id=%d',(int)$b['leader_id']),ARRAY_A);if(!$w)$wpdb->insert(self::table('wallets'),['leader_id'=>$b['leader_id']]);$w=$wpdb->get_row($wpdb->prepare('SELECT * FROM '.self::table('wallets').' WHERE leader_id=%d',(int)$b['leader_id']),ARRAY_A);$new=round((float)$w['available']+(float)$b['net_amount'],2);$wpdb->update(self::table('wallets'),['available'=>$new,'lifetime_earnings'=>(float)$w['lifetime_earnings']+(float)$b['net_amount'],'updated_at'=>current_time('mysql')],['leader_id'=>$b['leader_id']]);$wpdb->insert(self::table('wallet_transactions'),['leader_id'=>$b['leader_id'],'type'=>'booking','reference'=>$b['booking_ref'],'amount'=>$b['net_amount'],'description'=>'Booking '.$b['booking_ref'].' payment received','balance_after'=>$new]);}
  public static function routes(){
    register_rest_route('bubbahub/v1','/finance/paypal/(?P<id>\d+)/capture',['methods'=>'POST','callback'=>[__CLASS__,'paypal_capture'],'permission_callback'=>function(){return is_user_logged_in();}]);
    register_rest_route('bubbahub/v1','/finance/stripe/webhook',['methods'=>'POST','callback'=>[__CLASS__,'stripe_webhook'],'permission_callback'=>'__return_true']);
  }
  public static function intercept_payment($result,$server,$request){
    if($result!==null)return $result;$route=$request->get_route();if($request->get_method()!=='POST'||!preg_match('#^/bubbahub/v1/bookings/(\d+)/pay$#',$route,$m))return $result;
    $b=self::booking((int)$m[1],get_current_user_id());if(!$b)return new WP_Error('not_found','Booking not found',['status'=>404]);
    if($b['payment_method']==='stripe')return self::stripe_checkout($b);
    if($b['payment_method']==='paypal')return self::paypal_order($b);
    return $result;
  }
  private static function stripe_checkout($b){$s=self::settings();if(empty($s['stripe_secret_key']))return new WP_Error('stripe_not_configured','Stripe is not configured. Add the Stripe secret key in BubbaHub → Payments & Wallet.',['status'=>503]);$amount=(int)round(((float)$b['gross_amount'])*100);$success=add_query_arg(['bubbahub_payment'=>'success','booking'=>$b['id'],'ref'=>$b['booking_ref']],home_url('/'));$cancel=add_query_arg(['bubbahub_payment'=>'cancelled','booking'=>$b['id']],home_url('/'));$body=['mode'=>'payment','success_url'=>$success,'cancel_url'=>$cancel,'client_reference_id'=>$b['booking_ref'],'metadata[booking_id]'=>$b['id'],'metadata[booking_ref]'=>$b['booking_ref'],'line_items[0][price_data][currency]'=>strtolower($s['currency']??'gbp'),'line_items[0][price_data][product_data][name]'=>'BubbaHub booking '.$b['booking_ref'],'line_items[0][price_data][unit_amount]'=>$amount,'line_items[0][quantity]'=>1];$res=wp_remote_post('https://api.stripe.com/v1/checkout/sessions',['timeout'=>20,'headers'=>['Authorization'=>'Bearer '.$s['stripe_secret_key'],'Content-Type'=>'application/x-www-form-urlencoded'],'body'=>http_build_query($body)]);if(is_wp_error($res))return new WP_Error('stripe_error',$res->get_error_message(),['status'=>502]);$out=json_decode(wp_remote_retrieve_body($res),true);if(empty($out['url']))return new WP_Error('stripe_error',$out['error']['message']??'Stripe could not create checkout.',['status'=>502]);global $wpdb;$wpdb->update(self::table('bookings'),['provider_ref'=>$out['id']],['id'=>$b['id']]);return ['provider'=>'stripe','checkout_url'=>esc_url_raw($out['url']),'session_id'=>$out['id'],'booking_id'=>(int)$b['id']];}
  private static function paypal_token(){ $s=self::settings();if(empty($s['paypal_client_id'])||empty($s['paypal_client_secret']))return new WP_Error('paypal_not_configured','PayPal is not configured. Add the client ID and secret in BubbaHub → Payments & Wallet.',['status'=>503]);$base=(!empty($s['paypal_sandbox']))?'https://api-m.sandbox.paypal.com':'https://api-m.paypal.com';$res=wp_remote_post($base.'/v1/oauth2/token',['timeout'=>20,'headers'=>['Authorization'=>'Basic '.base64_encode($s['paypal_client_id'].':'.$s['paypal_client_secret']),'Content-Type'=>'application/x-www-form-urlencoded'],'body'=>'grant_type=client_credentials');if(is_wp_error($res))return new WP_Error('paypal_error',$res->get_error_message(),['status'=>502]);$out=json_decode(wp_remote_retrieve_body($res),true);return empty($out['access_token'])?new WP_Error('paypal_error',$out['error_description']??'PayPal authentication failed.',['status'=>502]):['token'=>$out['access_token'],'base'=>$base];}
  private static function paypal_order($b){$tok=self::paypal_token();if(is_wp_error($tok))return $tok;$s=self::settings();$body=['intent'=>'CAPTURE','purchase_units'=>[['reference_id'=>$b['booking_ref'],'custom_id'=>(string)$b['id'],'description'=>'BubbaHub booking '.$b['booking_ref'],'amount'=>['currency_code'=>$s['currency']??'GBP','value'=>number_format((float)$b['gross_amount'],2,'.','')]]]];$res=wp_remote_post($tok['base'].'/v2/checkout/orders',['timeout'=>20,'headers'=>['Authorization'=>'Bearer '.$tok['token'],'Content-Type'=>'application/json'],'body'=>wp_json_encode($body)]);if(is_wp_error($res))return new WP_Error('paypal_error',$res->get_error_message(),['status'=>502]);$out=json_decode(wp_remote_retrieve_body($res),true);if(empty($out['id']))return new WP_Error('paypal_error',$out['message']??'PayPal could not create the order.',['status'=>502]);global $wpdb;$wpdb->update(self::table('bookings'),['provider_ref'=>$out['id']],['id'=>$b['id']]);$approve='';foreach(($out['links']??[]) as $link)if(($link['rel']??'')==='approve')$approve=$link['href'];return ['provider'=>'paypal','order_id'=>$out['id'],'approval_url'=>$approve,'checkout_url'=>$approve,'booking_id'=>(int)$b['id']];}
  public static function paypal_capture($r){$id=absint($r['id']);$b=self::booking($id,get_current_user_id());if(!$b)return new WP_Error('not_found','Booking not found',['status'=>404]);$tok=self::paypal_token();if(is_wp_error($tok))return $tok;$order=sanitize_text_field($r->get_json_params()['order_id']??$b['provider_ref']);if(!$order)return new WP_Error('paypal_order','PayPal order ID is required.',['status'=>400]);$res=wp_remote_post($tok['base'].'/v2/checkout/orders/'.rawurlencode($order).'/capture',['timeout'=>20,'headers'=>['Authorization'=>'Bearer '.$tok['token'],'Content-Type'=>'application/json'],'body'=>'{}']);if(is_wp_error($res))return new WP_Error('paypal_error',$res->get_error_message(),['status'=>502]);$out=json_decode(wp_remote_retrieve_body($res),true);if(($out['status']??'')!=='COMPLETED')return new WP_Error('paypal_capture',$out['message']??'PayPal capture was not completed.',['status'=>502]);self::mark_paid($b,$order);return ['success'=>true,'status'=>'paid','booking_id'=>$id,'provider_ref'=>$order];}
  public static function stripe_webhook($r){$s=self::settings();$payload=$r->get_body();$sig=$_SERVER['HTTP_STRIPE_SIGNATURE']??'';$secret=$s['stripe_webhook_secret']??'';if($secret&& !self::verify_stripe_signature($payload,$sig,$secret))return new WP_Error('stripe_signature','Invalid Stripe webhook signature.',['status'=>400]);$event=json_decode($payload,true);$type=$event['type']??'';if(in_array($type,['checkout.session.completed','checkout.session.async_payment_succeeded'],true)){$obj=$event['data']['object']??[];$id=absint($obj['metadata']['booking_id']??0);if($id){$b=self::booking($id);if($b)self::mark_paid($b,$obj['id']??'stripe');}}return ['received'=>true];}
  private static function verify_stripe_signature($payload,$header,$secret){$parts=[];foreach(explode(',',$header) as $piece){$x=explode('=',$piece,2);if(count($x)===2)$parts[$x[0]]=$x[1];}if(empty($parts['t'])||empty($parts['v1']))return false;$signed=$parts['t'].'.'.$payload;$expected=hash_hmac('sha256',$signed,$secret);return hash_equals($expected,$parts['v1'])&&(time()-(int)$parts['t']<300);}
  public static function process_queued_payouts(){global $wpdb;$rows=$wpdb->get_results("SELECT * FROM ".self::table('payouts')." WHERE status='queued' ORDER BY id ASC LIMIT 20",ARRAY_A);foreach($rows as $p){$settings=self::settings();$method=$p['method'];if($method==='bank_transfer')continue;$wpdb->update(self::table('payouts'),['status'=>'processing'],['id'=>$p['id']]);$ok=false;$provider='';if($method==='stripe'&&!empty($settings['stripe_secret_key'])){$ps=(array)get_user_meta($p['leader_id'],'bubbahub_payout_settings',true);$dest=sanitize_text_field($ps['stripe_connect_account']??'');if($dest){$res=wp_remote_post('https://api.stripe.com/v1/transfers',['timeout'=>20,'headers'=>['Authorization'=>'Bearer '.$settings['stripe_secret_key'],'Content-Type'=>'application/x-www-form-urlencoded'],'body'=>http_build_query(['amount'=>(int)round($p['amount']*100),'currency'=>strtolower($settings['currency']??'gbp'),'destination'=>$dest,'metadata[payout_id]'=>$p['id']])]);$out=!is_wp_error($res)?json_decode(wp_remote_retrieve_body($res),true):[];$ok=!empty($out['id']);$provider=$out['id']??'';}}
    if($method==='paypal'){/* PayPal payouts require a live/sandbox Payouts-enabled app; leave queued rather than falsely marking a transfer paid. */}
    if($ok){$w=$wpdb->get_row($wpdb->prepare('SELECT * FROM '.self::table('wallets').' WHERE leader_id=%d',$p['leader_id']),ARRAY_A);$new=max(0,round((float)$w['available']-(float)$p['amount'],2));$wpdb->update(self::table('wallets'),['available'=>$new,'lifetime_payouts'=>(float)$w['lifetime_payouts']+(float)$p['amount'],'updated_at'=>current_time('mysql')],['leader_id'=>$p['leader_id']]);$wpdb->insert(self::table('wallet_transactions'),['leader_id'=>$p['leader_id'],'type'=>'payout','reference'=>$p['payout_ref'],'amount'=>-(float)$p['amount'],'description'=>'Payout processed','balance_after'=>$new]);$wpdb->update(self::table('payouts'),['status'=>'paid','provider_ref'=>$provider,'processed_at'=>current_time('mysql')],['id'=>$p['id']]);}else{$wpdb->update(self::table('payouts'),['status'=>'queued','reason'=>'Provider not configured or payout not yet processed.'],['id'=>$p['id']]);}}
  }
  public static function admin_menu(){add_submenu_page('bubbahub','Payments & Wallet','Payments & Wallet','manage_options','bubbahub-payment-settings',[__CLASS__,'page']);}
  public static function page(){if(!current_user_can('manage_options'))return;$s=self::settings();echo '<div class="wrap"><h1>BubbaHub Payments & Wallet</h1><p>Provider credentials are stored server-side. Never expose secret keys in JavaScript.</p><form method="post" action="'.esc_url(admin_url('admin-post.php')).'">'.wp_nonce_field('bh_provider_save','bh_provider_nonce',true,false).'<input type="hidden" name="action" value="bh_provider_save"><table class="form-table"><tr><th>Currency</th><td><input name="currency" value="'.esc_attr($s['currency']??'GBP').'" maxlength="3"></td></tr><tr><th>Stripe secret key</th><td><input class="regular-text" type="password" name="stripe_secret_key" value="'.esc_attr($s['stripe_secret_key']??'').'"></td></tr><tr><th>Stripe webhook secret</th><td><input class="regular-text" type="password" name="stripe_webhook_secret" value="'.esc_attr($s['stripe_webhook_secret']??'').'"></td></tr><tr><th>PayPal client ID</th><td><input class="regular-text" name="paypal_client_id" value="'.esc_attr($s['paypal_client_id']??'').'"></td></tr><tr><th>PayPal client secret</th><td><input class="regular-text" type="password" name="paypal_client_secret" value="'.esc_attr($s['paypal_client_secret']??'').'"></td></tr><tr><th>PayPal environment</th><td><select name="paypal_sandbox"><option value="1" '.selected(!empty($s['paypal_sandbox']),true,false).'>Sandbox</option><option value="0" '.selected(empty($s['paypal_sandbox']),true,false).'>Live</option></select></td></tr></table><p><button class="button button-primary">Save provider settings</button></p></form><h2>Bank transfer</h2><p>Bank transfer remains invoice-first and is never treated as an instant customer payment. Confirm receipt in Bookings & Payments before the leader wallet is credited.</p></div>';}
  public static function save(){if(!current_user_can('manage_options')||!check_admin_referer('bh_provider_save','bh_provider_nonce'))wp_die('Unauthorised');$s=self::settings();foreach(['currency','stripe_secret_key','stripe_webhook_secret','paypal_client_id','paypal_client_secret'] as $k)$s[$k]=sanitize_text_field(wp_unslash($_POST[$k]??''));$s['currency']=strtoupper(substr($s['currency']?:'GBP',0,3));$s['paypal_sandbox']=!empty($_POST['paypal_sandbox'])?1:0;update_option('bubbahub_finance_settings',$s);wp_safe_redirect(admin_url('admin.php?page=bubbahub-payment-settings&updated=1'));exit;}
}
BubbaHubFinanceProviders::init();
