<?php
if(!defined('ABSPATH'))exit;
class BubbaHubGoogleSync{
const OPTION='bubbahub_google_sync',CRON='bubbahub_google_sync_cron';
const MAIN_URL='https://script.google.com/macros/s/AKfycbwL70V_m3FIoxNTuc0MiI_tdAIfMlJrt0Zw62vnefNwctEmg5Pe93UhFaWzaRl3gTv1/exec';
const TERM_URL='https://script.google.com/macros/s/AKfycbzxEfyvcyb9oJ25nvWgrJqRuuvoh5tWoTp5uS1j1R8SUFJgNSVauawY35cVaWo6LBSH/exec';private static $importing=false;
public static function boot(){add_action('admin_menu',[__CLASS__,'menu'],30);add_action('admin_post_bubbahub_google_sync',[__CLASS__,'save_settings']);add_action(self::CRON,[__CLASS__,'sync']);add_action('init',[__CLASS__,'schedule']);add_action('save_post_bh_group',[__CLASS__,'save_post'],30,3);add_action('before_delete_post',[__CLASS__,'delete_hook'],20);add_filter('rest_post_dispatch',[__CLASS__,'rest_status'],20,3);add_action('wp_enqueue_scripts',[__CLASS__,'assets'],30);}
public static function schedule(){if(!wp_next_scheduled(self::CRON))wp_schedule_event(time()+300,'twicedaily',self::CRON);}
public static function settings(){return wp_parse_args(get_option(self::OPTION,[]),['main_url'=>self::MAIN_URL,'term_url'=>self::TERM_URL,'shared_secret'=>'','secure_api'=>0,'writeback'=>0,'auto_sync'=>1]);}
public static function menu(){add_submenu_page('bubbahub','Google Sheets Sync','Google Sheets Sync','manage_bubbahub','bubbahub-google-sync',[__CLASS__,'page']);}
public static function page(){if(!current_user_can('manage_bubbahub'))return;$s=self::settings();$n=sanitize_key($_GET['bh_google_sync']??'');echo '<div class="wrap"><h1>Google Sheets Sync</h1>';if($n==='success')echo '<div class="notice notice-success"><p>Google sync completed.</p></div>';if($n==='error')echo '<div class="notice notice-error"><p>Google sync failed.</p></div>';echo '<form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="bubbahub_google_sync">';wp_nonce_field('bubbahub_google_sync','bubbahub_google_nonce');echo '<table class="form-table"><tr><th>Listings API</th><td><input class="regular-text code" name="main_url" value="'.esc_attr($s['main_url']).'"></td></tr><tr><th>Term-time API</th><td><input class="regular-text code" name="term_url" value="'.esc_attr($s['term_url']).'"></td></tr><tr><th>Shared secret</th><td><input type="password" class="regular-text code" name="shared_secret" value="'.esc_attr($s['shared_secret']).'"><p>Same value as Google Script Property <code>BUBBAHUB_SHARED_SECRET</code>.</p></td></tr><tr><th>Secure API</th><td><label><input type="checkbox" name="secure_api" value="1" '.checked($s['secure_api'],1,false).'> Signed POST Listings API</label></td></tr><tr><th>Write-back</th><td><label><input type="checkbox" name="writeback" value="1" '.checked($s['writeback'],1,false).'> Leader changes sync to Google</label></td></tr><tr><th>Automatic sync</th><td><label><input type="checkbox" name="auto_sync" value="1" '.checked($s['auto_sync'],1,false).'> Twice daily</label></td></tr></table><p><button class="button button-primary">Save settings &amp; sync now</button></p></form><p>Identity: permanent Google <code>id</code> + WordPress <code>wp_username</code>. Titles are only a legacy fallback.</p></div>';}
public static function save_settings(){if(!current_user_can('manage_bubbahub')||!check_admin_referer('bubbahub_google_sync','bubbahub_google_nonce'))wp_die('Permission denied.');$s=self::settings();foreach(['main_url','term_url']as$k)$s[$k]=esc_url_raw(wp_unslash($_POST[$k]??$s[$k]));$s['shared_secret']=sanitize_text_field(wp_unslash($_POST['shared_secret']??$s['shared_secret']));$s['secure_api']=!empty($_POST['secure_api'])?1:0;$s['writeback']=!empty($_POST['writeback'])&&$s['secure_api']?1:0;$s['auto_sync']=!empty($_POST['auto_sync'])?1:0;update_option(self::OPTION,$s);$ok=self::sync();wp_safe_redirect(add_query_arg(['page'=>'bubbahub-google-sync','bh_google_sync'=>$ok?'success':'error'],admin_url('admin.php')));exit;}
private static function key($k){return sanitize_title_with_dashes(strtolower(trim((string)$k)));}private static function val($r,$a){foreach($a as$x){$k=self::key($x);if(isset($r[$k])&&$r[$k]!=='')return$r[$k];}return'';}private static function yes($v){return is_bool($v)?$v:in_array(strtolower(trim((string)$v)),['1','true','yes','y','on'],true);}private static function date($v){if(!$v)return'';$v=trim((string)$v);foreach(['Y-m-d','d/m/Y','d-m-Y','d.m.Y','Y/m/d','j/n/Y','j-n-Y']as$f){$d=DateTimeImmutable::createFromFormat('!'.$f,$v,new DateTimeZone('Europe/London'));if($d&&$d->format($f)===$v)return$d->format('Y-m-d');}$t=strtotime($v);return$t?wp_date('Y-m-d',$t,new DateTimeZone('Europe/London')):'';}
private static function rows($d){foreach(['data','rows','groups','listings']as$c)if(isset($d[$c])&&is_array($d[$c])){$d=$d[$c];break;}if(!is_array($d))return[];$o=[];foreach($d as$r){if(!is_array($r))continue;$x=[];foreach($r as$k=>$v)$x[self::key($k)]=is_scalar($v)?trim((string)$v):$v;if($x)$o[]=$x;}return$o;}
private static function signed($url,$action,$payload=[]){$s=self::settings();if(!$s['shared_secret'])return[];$t=time();$n=wp_generate_uuid4();$j=wp_json_encode($payload,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);$b=['action'=>$action,'timestamp'=>$t,'nonce'=>$n,'payload'=>$payload,'signature'=>hash_hmac('sha256',$action."\n".$t."\n".$n."\n".$j,$s['shared_secret'])];$r=wp_remote_post($url,['timeout'=>30,'headers'=>['Accept'=>'application/json','Content-Type'=>'application/json'],'body'=>wp_json_encode($b),'user-agent'=>'BubbaHub/'.BUBBAHUB_VERSION]);if(is_wp_error($r))return[];$d=json_decode(wp_remote_retrieve_body($r),true);if(wp_remote_retrieve_response_code($r)<200||wp_remote_retrieve_response_code($r)>=300||!is_array($d))return[];return isset($d['success'])&&!$d['success']?[]:$d;}
private static function get_json($url){$s=self::settings();if($s['secure_api']){$d=self::signed($url,'list',[]);return$d?self::rows($d):[];}$r=wp_remote_get($url,['timeout'=>30,'headers'=>['Accept'=>'application/json'],'user-agent'=>'BubbaHub/'.BUBBAHUB_VERSION]);if(is_wp_error($r))return[];$d=json_decode(wp_remote_retrieve_body($r),true);return is_array($d)?self::rows($d):[];}
private static function merge($a,$b){if(!$b)return$a;$i=[];foreach($b as$r){$id=self::val($r,['id','listing_id','group_id']);$n=self::val($r,['name','title','group_name']);if($id!=='')$i['i:'.strtolower($id)]=$r;if($n!=='')$i['n:'.sanitize_title($n)]=$r;}foreach($a as&$r){$id=self::val($r,['id','listing_id','group_id']);$n=self::val($r,['name','title','group_name']);$e=$id!==''?($i['i:'.strtolower($id)]??[]):($i['n:'.sanitize_title($n)]??[]);if($e)$r=array_merge($e,$r);}return$a;}
private static function fields(){return['wp_username'=>['wp_username','organizer_username','organiser_username'],'images'=>['images'],'tags'=>['tags','tag'],'category'=>['category'],'featured'=>['is_featured','featured'],'street'=>['address','street'],'city'=>['city','town'],'region'=>['region','county'],'zip'=>['zip','postcode'],'latitude'=>['manual_lat','latitude','lat'],'longitude'=>['manual_lng','longitude','lng','lon'],'timetable'=>['timetable'],'business_hours'=>['openinghours','opening hours','business_hours'],'website'=>['website','url'],'email'=>['email'],'facebook'=>['facebook'],'instagram'=>['instagram'],'is_free'=>['is_free','free'],'price'=>['price','cost'],'term_time'=>['term time','term_time','termtime'],'age_range'=>['age range','age_range'],'session_length'=>['session length','session_length'],'day'=>['day','days'],'sen'=>['sen'],'start_date'=>['start_date','start date'],'end_date'=>['end_date','end date']];}
public static function sync(){$s=self::settings();if(!$s['auto_sync']&&wp_doing_cron())return false;$a=self::get_json($s['main_url']);if(!$a)return false;$a=self::merge($a,self::get_json($s['term_url']));$c=0;self::$importing=true;try{foreach($a as$r){$title=sanitize_text_field(self::val($r,['title','name','group_name','listing_name']));if(!$title)continue;$gid=sanitize_text_field(self::val($r,['id','listing_id','group_id']));$u=sanitize_user(self::val($r,['wp_username','organizer_username','organiser_username']));$id=$gid?absint(get_posts(['post_type'=>'bh_group','post_status'=>'any','posts_per_page'=>1,'fields'=>'ids','meta_key'=>'_bubbahub_google_id','meta_value'=>$gid])[0]??0):0;if($id&&$u){$old=sanitize_user(get_post_meta($id,'_bubbahub_google_wp_username',true));if($old&&strcasecmp($old,$u)!==0)continue;}if(!$id)$id=absint(get_page_by_title($title,OBJECT,'bh_group')->ID??0);$args=['post_title'=>$title,'post_type'=>'bh_group','post_status'=>'publish'];$d=self::val($r,['description','content','post_content']);if($d!=='')$args['post_content']=wp_kses_post($d);if($u){$x=get_user_by('login',$u);if($x)$args['post_author']=$x->ID;}if($id){$args['ID']=$id;wp_update_post($args);}else{$id=wp_insert_post(wp_slash($args),true);if(is_wp_error($id))continue;}if($gid)update_post_meta($id,'_bubbahub_google_id',$gid);if($u){update_post_meta($id,'_bubbahub_google_wp_username',$u);update_post_meta($id,'_bubbahub_organizer_username',$u);}foreach(self::fields()as$f=>$a){if($f==='wp_username')continue;$v=self::val($r,$a);if(in_array($f,['start_date','end_date'],true))$v=self::date($v);if(in_array($f,['term_time','featured','is_free'],true))$v=self::yes($v)?'1':'0';if($v!=='')update_post_meta($id,'_bubbahub_'.$f,is_scalar($v)?sanitize_text_field((string)$v):$v);}update_post_meta($id,'_bubbahub_google_last_sync',current_time('mysql'));$c++;}}finally{self::$importing=false;}update_option(self::OPTION.'_last_sync',['time'=>current_time('mysql'),'count'=>$c]);return$c>0;}
private static function payload($id){$p=get_post($id);if(!$p||$p->post_type!=='bh_group')return[];$u=sanitize_user(get_post_meta($id,'_bubbahub_google_wp_username',true));if(!$u&&$p->post_author){$x=get_userdata($p->post_author);if($x)$u=$x->user_login;}$m=function($k,$d='')use($id){$v=get_post_meta($id,'_bubbahub_'.$k,true);return$v===''?$d:$v;};return['id'=>(string)get_post_meta($id,'_bubbahub_google_id',true),'wp_username'=>$u,'title'=>get_the_title($id),'images'=>$m('images'),'description'=>$p->post_content,'tags'=>$m('tags'),'category'=>$m('category'),'is_featured'=>$m('featured','0'),'address'=>$m('street'),'city'=>$m('city'),'region'=>$m('region'),'zip'=>$m('zip'),'manual_lat'=>$m('latitude'),'manual_lng'=>$m('longitude'),'timetable'=>$m('timetable'),'openinghours'=>$m('business_hours'),'website'=>$m('website'),'email'=>$m('email'),'facebook'=>$m('facebook'),'instagram'=>$m('instagram'),'is_free'=>$m('is_free','0'),'price'=>$m('price'),'term time'=>$m('term_time'),'age range'=>$m('age_range'),'session length'=>$m('session_length'),'day'=>$m('day'),'sen'=>$m('sen')];}
private static function can_write($id){$s=self::settings();if(!$s['secure_api']||!$s['writeback']||!is_user_logged_in())return false;$p=get_post($id);$u=sanitize_user(get_post_meta($id,'_bubbahub_google_wp_username',true));if(!$u&&$p&&$p->post_author){$x=get_userdata($p->post_author);if($x)$u=$x->user_login;}if(current_user_can('manage_bubbahub'))return true;$me=wp_get_current_user();return$u&&$me->user_login===$u&&current_user_can('edit_bubbahub_items');}
public static function push($id){if(!self::can_write($id))return false;$p=self::payload($id);return!empty($p['id'])&&(bool)self::signed(self::settings()['main_url'],'update',$p);}
public static function create($id){$s=self::settings();if(!$s['secure_api']||!$s['writeback'])return false;$p=self::payload($id);unset($p['id']);if(!$p['wp_username'])return false;$r=self::signed($s['main_url'],'create',$p);$gid=$r['id']??($r['listing']['id']??'');if($gid==='')return false;update_post_meta($id,'_bubbahub_google_id',sanitize_text_field((string)$gid));return true;}
public static function remove($id){$s=self::settings();if(!$s['secure_api']||!$s['writeback'])return false;$p=self::payload($id);return!empty($p['id'])&&!empty($p['wp_username'])&&(bool)self::signed($s['main_url'],'delete',['id'=>$p['id'],'wp_username'=>$p['wp_username']]);}
public static function save_post($id,$p,$update){if(self::$importing||wp_is_post_revision($id)||wp_is_post_autosave($id)||$p->post_status==='auto-draft')return;$s=self::settings();if(!$s['secure_api']||!$s['writeback'])return;get_post_meta($id,'_bubbahub_google_id',true)?self::push($id):($update?self::create($id):null);}
public static function delete_hook($id){if(!self::$importing&&get_post_type($id)==='bh_group')self::remove($id);}
public static function group_status($id){if(get_post_type($id)!=='bh_group'||!self::yes(get_post_meta($id,'_bubbahub_term_time',true)))return null;$a=self::date(get_post_meta($id,'_bubbahub_start_date',true));$b=self::date(get_post_meta($id,'_bubbahub_end_date',true));if(!$a||!$b)return['key'=>'inactive','label'=>'Inactive','class'=>'bh-status-inactive'];$n=new DateTimeImmutable('today',new DateTimeZone('Europe/London'));return$n>=new DateTimeImmutable($a,new DateTimeZone('Europe/London'))&&$n<=new DateTimeImmutable($b,new DateTimeZone('Europe/London'))?['key'=>'active','label'=>'Active','class'=>'bh-status-active']:['key'=>'inactive','label'=>'Inactive','class'=>'bh-status-inactive'];}
public static function rest_status($r,$s,$q){if(!($r instanceof WP_REST_Response))return$r;$route=$q->get_route();if(strpos($route,'/bubbahub/v1/groups')!==0&&strpos($route,'/bubbahub/v1/bootstrap')!==0)return$r;$d=$r->get_data();$f=function($x){if(is_array($x)&&!empty($x['id']))$x['activity_status']=self::group_status((int)$x['id']);return$x;};if(isset($d['groups'])&&is_array($d['groups']))$d['groups']=array_map($f,$d['groups']);elseif(isset($d[0]))$d=array_map($f,$d);$r->set_data($d);return$r;}
public static function assets(){$p=get_post();if(!(is_front_page()||(is_singular()&&has_shortcode($p->post_content??'','bubba_hub'))))return;wp_enqueue_style('bubbahub-group-status',BUBBAHUB_URL.'assests/css/group-status.css',[],BUBBAHUB_VERSION);wp_enqueue_script('bubbahub-group-status',BUBBAHUB_URL.'assests/js/group-status.js',[],BUBBAHUB_VERSION,true);wp_localize_script('bubbahub-group-status','BubbaHubStatusConfig',['api'=>esc_url_raw(rest_url('bubbahub/v1/groups'))]);}}
BubbaHubGoogleSync::boot();